copyright = "by Michael Blatherwick"
title = "minis.cool"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[params]
  defaultTheme = "dark"
  description = "My cool minis and my adventures with them"
  title = "minis.cool"
  logo = "/images/logo.png"