baseURL: https://minis.cool
title: minis.cool
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/preview.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Cool photos of cool minis
  # copyright: All rights reserved
  author: Michael Blatherwick
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        minis: 3
      mobile:
        minis: 3
  homepage: "/" # homepage link, mostly same with menu.main[0]
  specialPages:
    - minis
    - /
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: 'minis.cool'
  disableRadius: true
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

# menu:
#   main:
#     - name: photos
#       url: /
#       weight: 1